---
title: "Mortgages assignment"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Define initial parametrs

```{r Define initial parametrs}
# Initial deposit 
deposit = 10000
  
# Interest rate
i.rate = 0.06
  
# Time in years
t.years = 1

# Time in months
t.months = t.years * 12
```

## Future value

```{r Future value }
# Future value 
fv = deposit*(1 + i.rate)^(t.years)
eay = (fv - deposit)/deposit
list(fv, eay)

# Future value (compund month)
fv.cm = deposit*(1 + i.rate/12)^(t.months)
eay.cm = (fv.cm - deposit)/deposit
list(fv.cm, eay.cm)

```


```{r Present value}
fv = 10616.78
i.rate = 0.06
t.years = 1
t.months = t.years * 12

# Present value
pv = fv*(1/(1+i.rate)^(t.years))
pv

# Present value (compund month)
pv = fv*(1/(1+i.rate/12)^(t.months))
```

## Annuity

```{r Annuity}
annuity = function(payment,i.rate,t.years){
  period = seq(1:(t.years-1))
  fv = payment*sum((1 + i.rate)^period) + payment
  return(fv)
}

annuity.monthly = function(payment,i.rate,t.years){
  t.months = t.years * 12
  payment = payment/12
  period = seq(1:(t.months-1))
  fv = payment*sum((1 + i.rate/12)^period) + payment
  return(fv)
}

i.rate = 0.08
t.years = 5
payment = 2400

annuity(payment,i.rate,t.years)
annuity.monthly(payment,i.rate,t.years)
```

## Present value of annuity

```{r Present value of annuity}
annuity.pv = function(payment,i.rate,t.years){
  period = seq(1:(t.years))
  fv = payment*sum(1/(1 + i.rate)^period)
  return(fv)
}

annuity.monthly.pv = function(payment,i.rate,t.years){
  t.months = t.years * 12
  payment = payment/12
  period = seq(1:(t.months))
  fv = payment*sum(1/(1 + i.rate/12)^period)
  return(fv)
}

i.rate = 0.08
t.years = 0.5
payment = 300*12

annuity.pv(payment,i.rate,t.years)
annuity.monthly.pv(payment,i.rate,t.years)
```

## Accumulation of a Future Sum

```{r Accumulation of a Future Sum}

```


